--[=[
 d888b  db    db d888888b      .d888b.      db      db    db  .d8b.  
88' Y8b 88    88   `88'        VP  `8D      88      88    88 d8' `8b 
88      88    88    88            odD'      88      88    88 88ooo88 
88  ooo 88    88    88          .88'        88      88    88 88~~~88 
88. ~8~ 88b  d88   .88.        j88.         88booo. 88b  d88 88   88    @uniquadev
 Y888P  ~Y8888P' Y888888P      888888D      Y88888P ~Y8888P' YP   YP  CONVERTER 

designed using localmaze gui creator
]=]

-- Instances: 48 | Scripts: 2 | Modules: 0 | Tags: 0
local LMG2L = {};

-- Players.giruoh_jgry.PlayerGui.ScreenGui
LMG2L["ScreenGui_1"] = Instance.new("ScreenGui", game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui"));
LMG2L["ScreenGui_1"]["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling;


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame
LMG2L["Frame_2"] = Instance.new("Frame", LMG2L["ScreenGui_1"]);
LMG2L["Frame_2"]["BorderSizePixel"] = 2;
LMG2L["Frame_2"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["Frame_2"]["BorderMode"] = Enum.BorderMode.Middle;
LMG2L["Frame_2"]["Size"] = UDim2.new(0, 544, 0, 336);
LMG2L["Frame_2"]["Position"] = UDim2.new(0, 36, 0, 6);
LMG2L["Frame_2"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame script
LMG2L["Frame script_3"] = Instance.new("Frame", LMG2L["Frame_2"]);
LMG2L["Frame script_3"]["Visible"] = false;
LMG2L["Frame script_3"]["BorderSizePixel"] = 2;
LMG2L["Frame script_3"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["Frame script_3"]["BorderMode"] = Enum.BorderMode.Middle;
LMG2L["Frame script_3"]["Size"] = UDim2.new(0, 544, 0, 338);
LMG2L["Frame script_3"]["Position"] = UDim2.new(0, 0, 0, -2);
LMG2L["Frame script_3"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["Frame script_3"]["Name"] = [[Frame script]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame script.TextButton_c
LMG2L["TextButton_c_4"] = Instance.new("TextButton", LMG2L["Frame script_3"]);
LMG2L["TextButton_c_4"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_4"]["TextSize"] = 20;
LMG2L["TextButton_c_4"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_4"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_4"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButton_c_4"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_4"]["Text"] = [[executor]];
LMG2L["TextButton_c_4"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_4"]["Position"] = UDim2.new(0, 278, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame script.ScrollingFrame
LMG2L["ScrollingFrame_5"] = Instance.new("ScrollingFrame", LMG2L["Frame script_3"]);
LMG2L["ScrollingFrame_5"]["ScrollingDirection"] = Enum.ScrollingDirection.Y;
LMG2L["ScrollingFrame_5"]["BorderSizePixel"] = 0;
LMG2L["ScrollingFrame_5"]["TopImage"] = [[0]];
LMG2L["ScrollingFrame_5"]["MidImage"] = [[0]];
LMG2L["ScrollingFrame_5"]["VerticalScrollBarInset"] = Enum.ScrollBarInset.ScrollBar;
LMG2L["ScrollingFrame_5"]["BackgroundColor3"] = Color3.fromRGB(131, 131, 131);
LMG2L["ScrollingFrame_5"]["BottomImage"] = [[0]];
LMG2L["ScrollingFrame_5"]["Size"] = UDim2.new(0, 238, 0, 270);
LMG2L["ScrollingFrame_5"]["ScrollBarImageColor3"] = Color3.fromRGB(0, 0, 0);
LMG2L["ScrollingFrame_5"]["Position"] = UDim2.new(0, 2, 0, 64);
LMG2L["ScrollingFrame_5"]["ScrollBarThickness"] = 1;


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame script.ScrollingFrame.UIListLayout
LMG2L["UIListLayout_6"] = Instance.new("UIListLayout", LMG2L["ScrollingFrame_5"]);



-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame script.ScrollingFrame.TextButton
LMG2L["TextButton_7"] = Instance.new("TextButton", LMG2L["ScrollingFrame_5"]);
LMG2L["TextButton_7"]["BorderSizePixel"] = 0;
LMG2L["TextButton_7"]["TextSize"] = 12;
LMG2L["TextButton_7"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_7"]["BackgroundColor3"] = Color3.fromRGB(47, 47, 47);
LMG2L["TextButton_7"]["Size"] = UDim2.new(0, 238, 0, 20);
LMG2L["TextButton_7"]["Text"] = [[script]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame script.TextButton_c
LMG2L["TextButton_c_8"] = Instance.new("TextButton", LMG2L["Frame script_3"]);
LMG2L["TextButton_c_8"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_8"]["TextSize"] = 20;
LMG2L["TextButton_c_8"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_8"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_8"]["Size"] = UDim2.new(0, 50, 0, 28);
LMG2L["TextButton_c_8"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_8"]["Text"] = [[×]];
LMG2L["TextButton_c_8"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_8"]["Position"] = UDim2.new(0, 492, 0, 0);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame script.TextButtonheom
LMG2L["TextButtonheom_9"] = Instance.new("TextButton", LMG2L["Frame script_3"]);
LMG2L["TextButtonheom_9"]["BorderSizePixel"] = 2;
LMG2L["TextButtonheom_9"]["TextSize"] = 20;
LMG2L["TextButtonheom_9"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButtonheom_9"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButtonheom_9"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButtonheom_9"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButtonheom_9"]["Text"] = [[Home]];
LMG2L["TextButtonheom_9"]["Name"] = [[TextButtonheom]];
LMG2L["TextButtonheom_9"]["Position"] = UDim2.new(0, 2, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame script.TextLabel
LMG2L["TextLabel_a"] = Instance.new("TextLabel", LMG2L["Frame script_3"]);
LMG2L["TextLabel_a"]["TextWrapped"] = true;
LMG2L["TextLabel_a"]["BorderSizePixel"] = 2;
LMG2L["TextLabel_a"]["TextSize"] = 15;
LMG2L["TextLabel_a"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel_a"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextLabel_a"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_a"]["Size"] = UDim2.new(0, 490, 0, 28);
LMG2L["TextLabel_a"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextLabel_a"]["Text"] = [[ A.S.P by 00script]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame script.TextButton_c
LMG2L["TextButton_c_b"] = Instance.new("TextButton", LMG2L["Frame script_3"]);
LMG2L["TextButton_c_b"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_b"]["TextSize"] = 20;
LMG2L["TextButton_c_b"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_b"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_b"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButton_c_b"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_b"]["Text"] = [[script]];
LMG2L["TextButton_c_b"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_b"]["Position"] = UDim2.new(0, 140, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame script.TextButton_c
LMG2L["TextButton_c_c"] = Instance.new("TextButton", LMG2L["Frame script_3"]);
LMG2L["TextButton_c_c"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_c"]["TextSize"] = 20;
LMG2L["TextButton_c_c"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_c"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_c"]["Size"] = UDim2.new(0, 128, 0, 28);
LMG2L["TextButton_c_c"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_c"]["Text"] = [[console]];
LMG2L["TextButton_c_c"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_c"]["Position"] = UDim2.new(0, 414, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.TextLabel fe
LMG2L["TextLabel fe_d"] = Instance.new("TextLabel", LMG2L["Frame_2"]);
LMG2L["TextLabel fe_d"]["TextWrapped"] = true;
LMG2L["TextLabel fe_d"]["BorderSizePixel"] = 2;
LMG2L["TextLabel fe_d"]["TextSize"] = 15;
LMG2L["TextLabel fe_d"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel fe_d"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextLabel fe_d"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel fe_d"]["Size"] = UDim2.new(0, 538, 0, 28);
LMG2L["TextLabel fe_d"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextLabel fe_d"]["Text"] = [[Fe: ON]];
LMG2L["TextLabel fe_d"]["Name"] = [[TextLabel fe]];
LMG2L["TextLabel fe_d"]["Position"] = UDim2.new(0, 2, 0, 128);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.neam
LMG2L["neam_e"] = Instance.new("TextLabel", LMG2L["Frame_2"]);
LMG2L["neam_e"]["TextWrapped"] = true;
LMG2L["neam_e"]["BorderSizePixel"] = 0;
LMG2L["neam_e"]["TextSize"] = 15;
LMG2L["neam_e"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["neam_e"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["neam_e"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["neam_e"]["BackgroundTransparency"] = 1;
LMG2L["neam_e"]["Size"] = UDim2.new(0, 478, 0, 28);
LMG2L["neam_e"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["neam_e"]["Text"] = [[...]];
LMG2L["neam_e"]["LayoutOrder"] = 1;
LMG2L["neam_e"]["Name"] = [[neam]];
LMG2L["neam_e"]["Position"] = UDim2.new(0, 62, 0, 64);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.neam.LocalScript
LMG2L["LocalScript_f"] = Instance.new("LocalScript", LMG2L["neam_e"]);



-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.TextLabel Day
LMG2L["TextLabel Day_10"] = Instance.new("TextLabel", LMG2L["Frame_2"]);
LMG2L["TextLabel Day_10"]["TextWrapped"] = true;
LMG2L["TextLabel Day_10"]["BorderSizePixel"] = 2;
LMG2L["TextLabel Day_10"]["TextSize"] = 15;
LMG2L["TextLabel Day_10"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel Day_10"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextLabel Day_10"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel Day_10"]["Size"] = UDim2.new(0, 538, 0, 28);
LMG2L["TextLabel Day_10"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextLabel Day_10"]["Text"] = [[Day:]];
LMG2L["TextLabel Day_10"]["Name"] = [[TextLabel Day]];
LMG2L["TextLabel Day_10"]["Position"] = UDim2.new(0, 2, 0, 96);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.TextLabel 00script
LMG2L["TextLabel 00script_11"] = Instance.new("TextLabel", LMG2L["Frame_2"]);
LMG2L["TextLabel 00script_11"]["TextWrapped"] = true;
LMG2L["TextLabel 00script_11"]["BorderSizePixel"] = 2;
LMG2L["TextLabel 00script_11"]["TextSize"] = 15;
LMG2L["TextLabel 00script_11"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel 00script_11"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextLabel 00script_11"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel 00script_11"]["Size"] = UDim2.new(0, 538, 0, 28);
LMG2L["TextLabel 00script_11"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextLabel 00script_11"]["Text"] = [[is script by 00script]];
LMG2L["TextLabel 00script_11"]["Name"] = [[TextLabel 00script]];
LMG2L["TextLabel 00script_11"]["Position"] = UDim2.new(0, 2, 0, 158);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.TextLabel neam
LMG2L["TextLabel neam_12"] = Instance.new("TextLabel", LMG2L["Frame_2"]);
LMG2L["TextLabel neam_12"]["TextWrapped"] = true;
LMG2L["TextLabel neam_12"]["BorderSizePixel"] = 2;
LMG2L["TextLabel neam_12"]["TextSize"] = 15;
LMG2L["TextLabel neam_12"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel neam_12"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextLabel neam_12"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel neam_12"]["Size"] = UDim2.new(0, 538, 0, 28);
LMG2L["TextLabel neam_12"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextLabel neam_12"]["Text"] = [[name:]];
LMG2L["TextLabel neam_12"]["Name"] = [[TextLabel neam]];
LMG2L["TextLabel neam_12"]["Position"] = UDim2.new(0, 2, 0, 64);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.TextButton_c
LMG2L["TextButton_c_13"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_c_13"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_13"]["TextSize"] = 20;
LMG2L["TextButton_c_13"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_13"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_13"]["Size"] = UDim2.new(0, 128, 0, 28);
LMG2L["TextButton_c_13"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_13"]["Text"] = [[console]];
LMG2L["TextButton_c_13"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_13"]["Position"] = UDim2.new(0, 414, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.TextButton_c
LMG2L["TextButton_c_14"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_c_14"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_14"]["TextSize"] = 20;
LMG2L["TextButton_c_14"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_14"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_14"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButton_c_14"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_14"]["Text"] = [[executor]];
LMG2L["TextButton_c_14"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_14"]["Position"] = UDim2.new(0, 278, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.TextButton_c
LMG2L["TextButton_c_15"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_c_15"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_15"]["TextSize"] = 20;
LMG2L["TextButton_c_15"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_15"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_15"]["Size"] = UDim2.new(0, 50, 0, 28);
LMG2L["TextButton_c_15"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_15"]["Text"] = [[×]];
LMG2L["TextButton_c_15"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_15"]["Position"] = UDim2.new(0, 492, 0, 0);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame console
LMG2L["Frame console_16"] = Instance.new("Frame", LMG2L["Frame_2"]);
LMG2L["Frame console_16"]["Visible"] = false;
LMG2L["Frame console_16"]["BorderSizePixel"] = 2;
LMG2L["Frame console_16"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["Frame console_16"]["BorderMode"] = Enum.BorderMode.Middle;
LMG2L["Frame console_16"]["Size"] = UDim2.new(0, 544, 0, 338);
LMG2L["Frame console_16"]["Position"] = UDim2.new(0, 0, 0, -2);
LMG2L["Frame console_16"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["Frame console_16"]["Name"] = [[Frame console]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame console.TextButton_c
LMG2L["TextButton_c_17"] = Instance.new("TextButton", LMG2L["Frame console_16"]);
LMG2L["TextButton_c_17"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_17"]["TextSize"] = 20;
LMG2L["TextButton_c_17"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_17"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_17"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButton_c_17"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_17"]["Text"] = [[executor]];
LMG2L["TextButton_c_17"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_17"]["Position"] = UDim2.new(0, 278, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame console.ScrollingFrame
LMG2L["ScrollingFrame_18"] = Instance.new("ScrollingFrame", LMG2L["Frame console_16"]);
LMG2L["ScrollingFrame_18"]["ScrollingDirection"] = Enum.ScrollingDirection.Y;
LMG2L["ScrollingFrame_18"]["BorderSizePixel"] = 0;
LMG2L["ScrollingFrame_18"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["ScrollingFrame_18"]["Size"] = UDim2.new(0, 536, 0, 270);
LMG2L["ScrollingFrame_18"]["Position"] = UDim2.new(0, 2, 0, 64);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame console.ScrollingFrame.TextLabel
LMG2L["TextLabel_19"] = Instance.new("TextLabel", LMG2L["ScrollingFrame_18"]);
LMG2L["TextLabel_19"]["BorderSizePixel"] = 0;
LMG2L["TextLabel_19"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel_19"]["TextYAlignment"] = Enum.TextYAlignment.Top;
LMG2L["TextLabel_19"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_19"]["Size"] = UDim2.new(0, 538, 0, 684);
LMG2L["TextLabel_19"]["Text"] = [[output]];
LMG2L["TextLabel_19"]["Position"] = UDim2.new(0, 0, 0, 2);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame console.TextButton_c
LMG2L["TextButton_c_1a"] = Instance.new("TextButton", LMG2L["Frame console_16"]);
LMG2L["TextButton_c_1a"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_1a"]["TextSize"] = 20;
LMG2L["TextButton_c_1a"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_1a"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_1a"]["Size"] = UDim2.new(0, 50, 0, 28);
LMG2L["TextButton_c_1a"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_1a"]["Text"] = [[×]];
LMG2L["TextButton_c_1a"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_1a"]["Position"] = UDim2.new(0, 492, 0, 0);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame console.TextButtonheom
LMG2L["TextButtonheom_1b"] = Instance.new("TextButton", LMG2L["Frame console_16"]);
LMG2L["TextButtonheom_1b"]["BorderSizePixel"] = 2;
LMG2L["TextButtonheom_1b"]["TextSize"] = 20;
LMG2L["TextButtonheom_1b"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButtonheom_1b"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButtonheom_1b"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButtonheom_1b"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButtonheom_1b"]["Text"] = [[Home]];
LMG2L["TextButtonheom_1b"]["Name"] = [[TextButtonheom]];
LMG2L["TextButtonheom_1b"]["Position"] = UDim2.new(0, 2, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame console.TextLabel
LMG2L["TextLabel_1c"] = Instance.new("TextLabel", LMG2L["Frame console_16"]);
LMG2L["TextLabel_1c"]["TextWrapped"] = true;
LMG2L["TextLabel_1c"]["BorderSizePixel"] = 2;
LMG2L["TextLabel_1c"]["TextSize"] = 15;
LMG2L["TextLabel_1c"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel_1c"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextLabel_1c"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_1c"]["Size"] = UDim2.new(0, 490, 0, 28);
LMG2L["TextLabel_1c"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextLabel_1c"]["Text"] = [[ A.S.P by 00script]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame console.TextButton_c
LMG2L["TextButton_c_1d"] = Instance.new("TextButton", LMG2L["Frame console_16"]);
LMG2L["TextButton_c_1d"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_1d"]["TextSize"] = 20;
LMG2L["TextButton_c_1d"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_1d"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_1d"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButton_c_1d"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_1d"]["Text"] = [[script]];
LMG2L["TextButton_c_1d"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_1d"]["Position"] = UDim2.new(0, 140, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame console.TextButton_c
LMG2L["TextButton_c_1e"] = Instance.new("TextButton", LMG2L["Frame console_16"]);
LMG2L["TextButton_c_1e"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_1e"]["TextSize"] = 20;
LMG2L["TextButton_c_1e"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_1e"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_1e"]["Size"] = UDim2.new(0, 128, 0, 28);
LMG2L["TextButton_c_1e"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_1e"]["Text"] = [[console]];
LMG2L["TextButton_c_1e"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_1e"]["Position"] = UDim2.new(0, 414, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel
LMG2L["ImageLabel_1f"] = Instance.new("ImageLabel", LMG2L["Frame_2"]);
LMG2L["ImageLabel_1f"]["BorderSizePixel"] = 0;
LMG2L["ImageLabel_1f"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
-- LMG2L["ImageLabel_1f"]["ImageContent"] = ;
LMG2L["ImageLabel_1f"]["Image"] = [[rbxassetid://136123048397887]];
LMG2L["ImageLabel_1f"]["Size"] = UDim2.new(0, 96, 0, 88);
LMG2L["ImageLabel_1f"]["BackgroundTransparency"] = 1;
LMG2L["ImageLabel_1f"]["Position"] = UDim2.new(0, 424, 0, 218);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.TextLabel
LMG2L["TextLabel_20"] = Instance.new("TextLabel", LMG2L["Frame_2"]);
LMG2L["TextLabel_20"]["TextWrapped"] = true;
LMG2L["TextLabel_20"]["BorderSizePixel"] = 2;
LMG2L["TextLabel_20"]["TextSize"] = 15;
LMG2L["TextLabel_20"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel_20"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextLabel_20"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_20"]["Size"] = UDim2.new(0, 490, 0, 28);
LMG2L["TextLabel_20"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextLabel_20"]["Text"] = [[ A.S.P by 00script]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.TextButtonheom
LMG2L["TextButtonheom_21"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButtonheom_21"]["BorderSizePixel"] = 2;
LMG2L["TextButtonheom_21"]["TextSize"] = 20;
LMG2L["TextButtonheom_21"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButtonheom_21"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButtonheom_21"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButtonheom_21"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButtonheom_21"]["Text"] = [[Home]];
LMG2L["TextButtonheom_21"]["Name"] = [[TextButtonheom]];
LMG2L["TextButtonheom_21"]["Position"] = UDim2.new(0, 2, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.TextButton_c
LMG2L["TextButton_c_22"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_c_22"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_22"]["TextSize"] = 20;
LMG2L["TextButton_c_22"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_22"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_22"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButton_c_22"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_22"]["Text"] = [[script]];
LMG2L["TextButton_c_22"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_22"]["Position"] = UDim2.new(0, 140, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor
LMG2L["Frame executor_23"] = Instance.new("Frame", LMG2L["Frame_2"]);
LMG2L["Frame executor_23"]["Visible"] = false;
LMG2L["Frame executor_23"]["BorderSizePixel"] = 2;
LMG2L["Frame executor_23"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["Frame executor_23"]["BorderMode"] = Enum.BorderMode.Middle;
LMG2L["Frame executor_23"]["Size"] = UDim2.new(0, 544, 0, 338);
LMG2L["Frame executor_23"]["Position"] = UDim2.new(0, 0, 0, -2);
LMG2L["Frame executor_23"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["Frame executor_23"]["Name"] = [[Frame executor]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor.TextButton2
LMG2L["TextButton2_24"] = Instance.new("TextButton", LMG2L["Frame executor_23"]);
LMG2L["TextButton2_24"]["TextWrapped"] = true;
LMG2L["TextButton2_24"]["BorderSizePixel"] = 0;
LMG2L["TextButton2_24"]["TextScaled"] = true;
LMG2L["TextButton2_24"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_24"]["Size"] = UDim2.new(0, 152, 0, 40);
LMG2L["TextButton2_24"]["Text"] = [[clear ]];
LMG2L["TextButton2_24"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_24"]["Position"] = UDim2.new(0, 158, 0, 294);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor.TextButton3
LMG2L["TextButton3_25"] = Instance.new("TextButton", LMG2L["Frame executor_23"]);
LMG2L["TextButton3_25"]["TextWrapped"] = true;
LMG2L["TextButton3_25"]["BorderSizePixel"] = 0;
LMG2L["TextButton3_25"]["TextScaled"] = true;
LMG2L["TextButton3_25"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton3_25"]["Size"] = UDim2.new(0, 152, 0, 40);
LMG2L["TextButton3_25"]["Text"] = [[load]];
LMG2L["TextButton3_25"]["Name"] = [[TextButton3]];
LMG2L["TextButton3_25"]["Position"] = UDim2.new(0, 312, 0, 294);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor.TextButton
LMG2L["TextButton_26"] = Instance.new("TextButton", LMG2L["Frame executor_23"]);
LMG2L["TextButton_26"]["TextWrapped"] = true;
LMG2L["TextButton_26"]["BorderSizePixel"] = 0;
LMG2L["TextButton_26"]["TextScaled"] = true;
LMG2L["TextButton_26"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_26"]["Size"] = UDim2.new(0, 152, 0, 40);
LMG2L["TextButton_26"]["Text"] = [[Execute]];
LMG2L["TextButton_26"]["Position"] = UDim2.new(0, 4, 0, 294);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor.TextButton_c
LMG2L["TextButton_c_27"] = Instance.new("TextButton", LMG2L["Frame executor_23"]);
LMG2L["TextButton_c_27"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_27"]["TextSize"] = 20;
LMG2L["TextButton_c_27"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_27"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_27"]["Size"] = UDim2.new(0, 128, 0, 28);
LMG2L["TextButton_c_27"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_27"]["Text"] = [[console]];
LMG2L["TextButton_c_27"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_27"]["Position"] = UDim2.new(0, 414, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor.TextButton_c
LMG2L["TextButton_c_28"] = Instance.new("TextButton", LMG2L["Frame executor_23"]);
LMG2L["TextButton_c_28"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_28"]["TextSize"] = 20;
LMG2L["TextButton_c_28"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_28"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_28"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButton_c_28"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_28"]["Text"] = [[executor]];
LMG2L["TextButton_c_28"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_28"]["Position"] = UDim2.new(0, 278, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor.TextButton_c
LMG2L["TextButton_c_29"] = Instance.new("TextButton", LMG2L["Frame executor_23"]);
LMG2L["TextButton_c_29"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_29"]["TextSize"] = 20;
LMG2L["TextButton_c_29"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_29"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_29"]["Size"] = UDim2.new(0, 50, 0, 28);
LMG2L["TextButton_c_29"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_29"]["Text"] = [[×]];
LMG2L["TextButton_c_29"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_29"]["Position"] = UDim2.new(0, 492, 0, 0);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor.TextButtonheom
LMG2L["TextButtonheom_2a"] = Instance.new("TextButton", LMG2L["Frame executor_23"]);
LMG2L["TextButtonheom_2a"]["BorderSizePixel"] = 2;
LMG2L["TextButtonheom_2a"]["TextSize"] = 20;
LMG2L["TextButtonheom_2a"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButtonheom_2a"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButtonheom_2a"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButtonheom_2a"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButtonheom_2a"]["Text"] = [[Home]];
LMG2L["TextButtonheom_2a"]["Name"] = [[TextButtonheom]];
LMG2L["TextButtonheom_2a"]["Position"] = UDim2.new(0, 2, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor.TextLabel
LMG2L["TextLabel_2b"] = Instance.new("TextLabel", LMG2L["Frame executor_23"]);
LMG2L["TextLabel_2b"]["TextWrapped"] = true;
LMG2L["TextLabel_2b"]["BorderSizePixel"] = 2;
LMG2L["TextLabel_2b"]["TextSize"] = 15;
LMG2L["TextLabel_2b"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel_2b"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextLabel_2b"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_2b"]["Size"] = UDim2.new(0, 490, 0, 28);
LMG2L["TextLabel_2b"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextLabel_2b"]["Text"] = [[ A.S.P by 00script]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor.TextButton_c
LMG2L["TextButton_c_2c"] = Instance.new("TextButton", LMG2L["Frame executor_23"]);
LMG2L["TextButton_c_2c"]["BorderSizePixel"] = 2;
LMG2L["TextButton_c_2c"]["TextSize"] = 20;
LMG2L["TextButton_c_2c"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c_2c"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["TextButton_c_2c"]["Size"] = UDim2.new(0, 134, 0, 28);
LMG2L["TextButton_c_2c"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["TextButton_c_2c"]["Text"] = [[script]];
LMG2L["TextButton_c_2c"]["Name"] = [[TextButton_c]];
LMG2L["TextButton_c_2c"]["Position"] = UDim2.new(0, 140, 0, 32);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor.ScrollingFrame
LMG2L["ScrollingFrame_2d"] = Instance.new("ScrollingFrame", LMG2L["Frame executor_23"]);
LMG2L["ScrollingFrame_2d"]["ScrollingDirection"] = Enum.ScrollingDirection.Y;
LMG2L["ScrollingFrame_2d"]["SizeConstraint"] = Enum.SizeConstraint.RelativeYY;
LMG2L["ScrollingFrame_2d"]["BorderSizePixel"] = 0;
LMG2L["ScrollingFrame_2d"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["ScrollingFrame_2d"]["VerticalScrollBarPosition"] = Enum.VerticalScrollBarPosition.Left;
LMG2L["ScrollingFrame_2d"]["Size"] = UDim2.new(0, 534, 0, 226);
LMG2L["ScrollingFrame_2d"]["ScrollBarImageColor3"] = Color3.fromRGB(8, 8, 8);
LMG2L["ScrollingFrame_2d"]["Position"] = UDim2.new(0, 4, 0, 66);
LMG2L["ScrollingFrame_2d"]["ScrollBarThickness"] = 1;
LMG2L["ScrollingFrame_2d"]["BackgroundTransparency"] = 1;


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.Frame executor.ScrollingFrame.TextBox
LMG2L["TextBox_2e"] = Instance.new("TextBox", LMG2L["ScrollingFrame_2d"]);
LMG2L["TextBox_2e"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextBox_2e"]["BorderSizePixel"] = 0;
LMG2L["TextBox_2e"]["TextSize"] = 12;
LMG2L["TextBox_2e"]["TextYAlignment"] = Enum.TextYAlignment.Top;
LMG2L["TextBox_2e"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextBox_2e"]["MultiLine"] = true;
LMG2L["TextBox_2e"]["ClearTextOnFocus"] = false;
LMG2L["TextBox_2e"]["PlaceholderText"] = [[--[ Insert the script here ] --]];
LMG2L["TextBox_2e"]["Size"] = UDim2.new(0, 534, 0, 682);
LMG2L["TextBox_2e"]["Text"] = [[]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.dea
LMG2L["dea_2f"] = Instance.new("TextLabel", LMG2L["Frame_2"]);
LMG2L["dea_2f"]["TextWrapped"] = true;
LMG2L["dea_2f"]["BorderSizePixel"] = 0;
LMG2L["dea_2f"]["TextSize"] = 15;
LMG2L["dea_2f"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["dea_2f"]["BackgroundColor3"] = Color3.fromRGB(65, 65, 65);
LMG2L["dea_2f"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["dea_2f"]["BackgroundTransparency"] = 1;
LMG2L["dea_2f"]["Size"] = UDim2.new(0, 480, 0, 28);
LMG2L["dea_2f"]["BorderColor3"] = Color3.fromRGB(255, 231, 0);
LMG2L["dea_2f"]["Text"] = [[...]];
LMG2L["dea_2f"]["Name"] = [[dea]];
LMG2L["dea_2f"]["Position"] = UDim2.new(0, 46, 0, 96);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.dea.LocalScript
LMG2L["LocalScript_30"] = Instance.new("LocalScript", LMG2L["dea_2f"]);



-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.neam.LocalScript
local function C_f()
	local script = LMG2L["LocalScript_f"];
	local player = game.Players.LocalPlayer	
	script.Parent.Text = player.Name	
end;
task.spawn(C_f);
-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.dea.LocalScript
local function C_30()
	local script = LMG2L["LocalScript_30"];
	local player = game.Players.LocalPlayer	
	local textLabel = script.Parent	
	
	textLabel.Text = tostring(player.AccountAge)	
end;
task.spawn(C_30);

-- GUI ทั้งหมด

-- ระบบปุ่มต่างๆ

-- AUTO SCRIPT BUTTONS
local scripts = {
    {"Speed Script", "ลิงก์"},
    {"Jump Script", "ลิงก์"},
    {"Fly Script", "ลิงก์"},
}

local frame = LMG2L["ScrollingFrame_22"]

for _, data in pairs(scripts) do

    local name = data[1]
    local url = data[2]

    local btn = Instance.new("TextButton")
    btn.Parent = frame

    btn.BorderSizePixel = 0
    btn.TextXAlignment = Enum.TextXAlignment.Left
    btn.TextSize = 12
    btn.TextColor3 = Color3.fromRGB(255,255,255)
    btn.BackgroundColor3 = Color3.fromRGB(81,81,81)
    btn.Size = UDim2.new(0,328,0,20)
    btn.Text = name

    btn.MouseButton1Click:Connect(function()

        local success, result = pcall(function()
            return loadstring(game:HttpGet(url))()
        end)

        if success then
            print(name.." loaded!")
        else
            warn(result)
        end

    end)

end

local MainFrame = LMG2L["Frame_2"]

local HomeFrame = MainFrame
local ScriptFrame = LMG2L["Frame script_3"]
local ExecutorFrame = LMG2L["Frame executor_23"]
local ConsoleFrame = LMG2L["Frame console_16"]

local function HideAll()
	ScriptFrame.Visible = false
	ExecutorFrame.Visible = false
	ConsoleFrame.Visible = false
end

-- ปุ่ม Script
LMG2L["TextButton_c_22"].MouseButton1Click:Connect(function()
	HideAll()
	ScriptFrame.Visible = true
end)

-- ปุ่ม Executor
LMG2L["TextButton_c_14"].MouseButton1Click:Connect(function()
	HideAll()
	ExecutorFrame.Visible = true
end)

-- ปุ่ม Console
LMG2L["TextButton_c_13"].MouseButton1Click:Connect(function()
	HideAll()
	ConsoleFrame.Visible = true
end)

-- ปุ่ม Home
LMG2L["TextButtonheom_21"].MouseButton1Click:Connect(function()
	HideAll()
end)


return LMG2L["ScreenGui_1"], require;
